const sampleBooks = [
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'Self Help',
    language: 'English',
    status: 'Reading',
    progress: 75,
    isFavourite: true,
    tags: ['Productivity', 'Psychology', 'Self Improvement'],
    notes: 'Key takeaway: You do not rise to the level of your goals. You fall to the level of your systems. The 4 laws of behavior change: Make it obvious, attractive, easy, and satisfying.',
    startedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    category: 'Philosophy',
    language: 'English',
    status: 'Finished',
    progress: 100,
    isFavourite: true,
    tags: ['Classic', 'Inspirational', 'Adventure'],
    notes: '“And, when you want something, all the universe conspires in helping you to achieve it.” Santiago’s journey across the Andalusian pastures to the Egyptian pyramids.',
    startedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'Godaan',
    author: 'Munshi Premchand',
    category: 'Fiction',
    language: 'Hindi',
    status: 'Reading',
    progress: 60,
    isFavourite: true,
    tags: ['Indian Literature', 'Classic', 'Social Realism'],
    notes: 'A profound masterpiece portraying the socio-economic deprivations of rural India through the life of Hori and Dhania. Premchand’s character depth is unmatched.',
    startedAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000)
  },
  {
    title: '1984',
    author: 'George Orwell',
    category: 'Science Fiction',
    language: 'English',
    status: 'Finished',
    progress: 100,
    isFavourite: true,
    tags: ['Dystopian', 'Political', 'Classic'],
    notes: 'Chilling critique of totalitarianism, surveillance states, and manipulation of truth. "War is peace. Freedom is slavery. Ignorance is strength."',
    startedAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 75 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'Gunahon Ka Devta',
    author: 'Dharamvir Bharati',
    category: 'Romance',
    language: 'Hindi',
    status: 'Finished',
    progress: 100,
    isFavourite: true,
    tags: ['Classic', 'Indian Literature', 'Emotional'],
    notes: 'The haunting and timeless love story of Chander and Sudha set against the nostalgic backdrop of Allahabad. Deeply emotional and poetic prose.',
    startedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    category: 'Fiction',
    language: 'English',
    status: 'Finished',
    progress: 100,
    isFavourite: false,
    tags: ['Drama', 'Historical Fiction', 'Friendship'],
    notes: '“For you, a thousand times over.” A devastating yet uplifting story of guilt, friendship, betrayal, and redemption in Kabul and California.',
    startedAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'The Motorcycle Diaries',
    author: 'Ernesto Che Guevara',
    category: 'Autobiography',
    language: 'English',
    status: 'Reading',
    progress: 45,
    isFavourite: false,
    tags: ['Travel', 'Memoir', 'Latin America'],
    notes: 'Youthful journey across South America on Norton 500 "La Poderosa". Fascinating look at Guevara before he became an iconic revolutionary.',
    startedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'Train to Pakistan',
    author: 'Khushwant Singh',
    category: 'History',
    language: 'English',
    status: 'Finished',
    progress: 100,
    isFavourite: true,
    tags: ['Partition', 'Indian Literature', 'Historical Fiction'],
    notes: 'Set in Mano Majra on the eve of the 1947 Partition. A gut-wrenching portrayal of humanity caught in communal frenzy.',
    startedAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupéry',
    category: 'Philosophy',
    language: 'English',
    status: 'Finished',
    progress: 100,
    isFavourite: true,
    tags: ['Classic', 'Fable', 'Short Reads'],
    notes: '“It is only with the heart that one can see rightly; what is essential is invisible to the eye.” One of the most tender books ever written.',
    startedAt: new Date(Date.now() - 80 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 78 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'A Man Called Ove',
    author: 'Fredrik Backman',
    category: 'Fiction',
    language: 'English',
    status: 'Not Started',
    progress: 0,
    isFavourite: false,
    tags: ['Heartwarming', 'Humor', 'Contemporary'],
    notes: 'Recommended by friends. A grumpy yet lovable old man whose routine is disrupted by new neighbors.',
    startedAt: null,
    finishedAt: null
  },
  {
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    category: 'History',
    language: 'English',
    status: 'Reading',
    progress: 30,
    isFavourite: false,
    tags: ['Anthropology', 'Science', 'Non-Fiction'],
    notes: 'Cognitive revolution, Agricultural revolution, and Scientific revolution. Examines how shared fictions enabled human cooperation at scale.',
    startedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'Deep Work',
    author: 'Cal Newport',
    category: 'Self Help',
    language: 'English',
    status: 'Finished',
    progress: 100,
    isFavourite: false,
    tags: ['Productivity', 'Focus', 'Career'],
    notes: 'Rules for focused success in a distracted world. The ability to perform deep work is becoming increasingly rare and simultaneously increasingly valuable.',
    startedAt: new Date(Date.now() - 70 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'Rashmirathi',
    author: 'Ramdhari Singh Dinkar',
    category: 'Poetry',
    language: 'Hindi',
    status: 'Finished',
    progress: 100,
    isFavourite: true,
    tags: ['Mahabharata', 'Epic Poetry', 'Indian Literature'],
    notes: '“जब नाश मनुज पर छाता है, पहले विवेक मर जाता है।” The sublime tale of Karna’s honor, valor, friendship with Duryodhana, and destiny.',
    startedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
    finishedAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000)
  },
  {
    title: 'Pachinko',
    author: 'Min Jin Lee',
    category: 'Fiction',
    language: 'English',
    status: 'Not Started',
    progress: 0,
    isFavourite: false,
    tags: ['Family Saga', 'Historical Fiction', 'Asia'],
    notes: 'Multi-generational epic following a Korean family in Japan through the 20th century.',
    startedAt: null,
    finishedAt: null
  }
];

module.exports = sampleBooks;
